name: Portfolio Deployment

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AKIA3Q6Y6RQVGRM7LQJK }}
        aws-secret-access-key: ${{ secrets.4ttXOb5IYh4CHHpsgY4/mRqnvI1p/QUcpUNnBai4 }}
        aws-region: ap-south-1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync . s3://portfolio-demo1994 --delete
